categories:
- name: GETTING STARTED
  commands:
  - create
  - delete
  - edit
  - explain
  - expose
  - get
  - run
  - set
- name: DEPLOY
  commands:
  - autoscale
  - rollout
  - scale
- name: CLUSTER MANAGEMENT
  commands:
  - certificate
  - cluster-info
  - cordon
  - drain
  - taint
  - top
  - uncordon
- name: ADVANCED COMMANDS
  commands:
  - apply
  - convert
  - diff
  - kustomize
  - patch
  - replace
  - wait
- name: TROUBLESHOOTING AND DEBUGGING
  commands:
  - attach
  - auth
  - cp
  - describe
  - exec
  - logs
  - port-forward
  - proxy
- name: SETTINGS AND USAGE
  commands:
  - annotate
  - completion
  - label
- name: OTHER
  commands:
  - alpha
  - api-resources
  - api-versions
  - config
  - options
  - plugin
  - version
- name: DEPRECATED COMMANDS
  commands:
  - rolling-update
